#!/usr/bin/env sh

# uncomment to make me a noop
test -f ~/.playmode && exit

# kill any process with a name listed  in ~/.distracting_apps
#cat ~/.distracting_apps | xargs -n1 pkill -e

# kill any process with a name listed in ~/distracting_sites
cat ~/.distracting_sites | xargs -P4 -n1 ~/bin/tabkill
